// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: dclient_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AlterAeon dclient RPC — telemetry payloads (HUD/state).
/// Package dclient_rpc, from dclient_rpc_messages.pb.cc in dclient_linux64 1.105-g64-rc2.
/// See alteraeon_rpc_NOTES.md for provenance. Scalar varints typed int32 (see notes);
/// numeric field names (fN) are NOT in the binary. String field names ARE exact.
/// Text-carrying fields are `bytes` (not `string`): AlterAeon game text is ANSI + Latin-1,
/// not valid UTF-8, and a `string` field would make SwiftProtobuf reject the whole message.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// hpbar = player status bars. Parser 0x1088b0: fields 1..6 all varint.
/// Almost certainly the three AlterAeon bars: hit/spell/move points, current+max.
nonisolated struct DclientRpc_hpbar_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// e.g. hp
  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  /// e.g. maxhp
  var f2: Int32 {
    get {_f2 ?? 0}
    set {_f2 = newValue}
  }
  /// Returns true if `f2` has been explicitly set.
  var hasF2: Bool {self._f2 != nil}
  /// Clears the value of `f2`. Subsequent reads from it will return its default value.
  mutating func clearF2() {self._f2 = nil}

  /// e.g. sp
  var f3: Int32 {
    get {_f3 ?? 0}
    set {_f3 = newValue}
  }
  /// Returns true if `f3` has been explicitly set.
  var hasF3: Bool {self._f3 != nil}
  /// Clears the value of `f3`. Subsequent reads from it will return its default value.
  mutating func clearF3() {self._f3 = nil}

  /// e.g. maxsp
  var f4: Int32 {
    get {_f4 ?? 0}
    set {_f4 = newValue}
  }
  /// Returns true if `f4` has been explicitly set.
  var hasF4: Bool {self._f4 != nil}
  /// Clears the value of `f4`. Subsequent reads from it will return its default value.
  mutating func clearF4() {self._f4 = nil}

  /// e.g. mv
  var f5: Int32 {
    get {_f5 ?? 0}
    set {_f5 = newValue}
  }
  /// Returns true if `f5` has been explicitly set.
  var hasF5: Bool {self._f5 != nil}
  /// Clears the value of `f5`. Subsequent reads from it will return its default value.
  mutating func clearF5() {self._f5 = nil}

  /// e.g. maxmv
  var f6: Int32 {
    get {_f6 ?? 0}
    set {_f6 = newValue}
  }
  /// Returns true if `f6` has been explicitly set.
  var hasF6: Bool {self._f6 != nil}
  /// Clears the value of `f6`. Subsequent reads from it will return its default value.
  mutating func clearF6() {self._f6 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
  fileprivate var _f2: Int32? = nil
  fileprivate var _f3: Int32? = nil
  fileprivate var _f4: Int32? = nil
  fileprivate var _f5: Int32? = nil
  fileprivate var _f6: Int32? = nil
}

/// enemy_hp = current target. Parser 0x10a090: exactly 2 fields.
nonisolated struct DclientRpc_enemy_hp_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact name from .rodata; may carry ANSI colour → bytes
  var enemyName: Data {
    get {_enemyName ?? Data()}
    set {_enemyName = newValue}
  }
  /// Returns true if `enemyName` has been explicitly set.
  var hasEnemyName: Bool {self._enemyName != nil}
  /// Clears the value of `enemyName`. Subsequent reads from it will return its default value.
  mutating func clearEnemyName() {self._enemyName = nil}

  /// varint — HP value/percentage
  var f2: Int32 {
    get {_f2 ?? 0}
    set {_f2 = newValue}
  }
  /// Returns true if `f2` has been explicitly set.
  var hasF2: Bool {self._f2 != nil}
  /// Clears the value of `f2`. Subsequent reads from it will return its default value.
  mutating func clearF2() {self._f2 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _enemyName: Data? = nil
  fileprivate var _f2: Int32? = nil
}

/// sky_and_time. Parser 0x109870: fields 1..5 varint, field 6 string.
nonisolated struct DclientRpc_sky_and_time: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  var f2: Int32 {
    get {_f2 ?? 0}
    set {_f2 = newValue}
  }
  /// Returns true if `f2` has been explicitly set.
  var hasF2: Bool {self._f2 != nil}
  /// Clears the value of `f2`. Subsequent reads from it will return its default value.
  mutating func clearF2() {self._f2 = nil}

  var f3: Int32 {
    get {_f3 ?? 0}
    set {_f3 = newValue}
  }
  /// Returns true if `f3` has been explicitly set.
  var hasF3: Bool {self._f3 != nil}
  /// Clears the value of `f3`. Subsequent reads from it will return its default value.
  mutating func clearF3() {self._f3 = nil}

  var f4: Int32 {
    get {_f4 ?? 0}
    set {_f4 = newValue}
  }
  /// Returns true if `f4` has been explicitly set.
  var hasF4: Bool {self._f4 != nil}
  /// Clears the value of `f4`. Subsequent reads from it will return its default value.
  mutating func clearF4() {self._f4 = nil}

  var f5: Int32 {
    get {_f5 ?? 0}
    set {_f5 = newValue}
  }
  /// Returns true if `f5` has been explicitly set.
  var hasF5: Bool {self._f5 != nil}
  /// Clears the value of `f5`. Subsequent reads from it will return its default value.
  mutating func clearF5() {self._f5 = nil}

  /// exact name; bytes for safety
  var printedTimeOfDayString: Data {
    get {_printedTimeOfDayString ?? Data()}
    set {_printedTimeOfDayString = newValue}
  }
  /// Returns true if `printedTimeOfDayString` has been explicitly set.
  var hasPrintedTimeOfDayString: Bool {self._printedTimeOfDayString != nil}
  /// Clears the value of `printedTimeOfDayString`. Subsequent reads from it will return its default value.
  mutating func clearPrintedTimeOfDayString() {self._printedTimeOfDayString = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
  fileprivate var _f2: Int32? = nil
  fileprivate var _f3: Int32? = nil
  fileprivate var _f4: Int32? = nil
  fileprivate var _f5: Int32? = nil
  fileprivate var _printedTimeOfDayString: Data? = nil
}

/// exp_to_level. Parser 0x108560: single field 1, accepts packed+unpacked varint
/// => repeated int32 (plausibly XP-to-next-level per class in a multiclass MUD).
nonisolated struct DclientRpc_exp_to_level: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: [Int32] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// icon_bar_data. Parser 0x108ca0: fields 1..6 all varint.
nonisolated struct DclientRpc_icon_bar_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  var f2: Int32 {
    get {_f2 ?? 0}
    set {_f2 = newValue}
  }
  /// Returns true if `f2` has been explicitly set.
  var hasF2: Bool {self._f2 != nil}
  /// Clears the value of `f2`. Subsequent reads from it will return its default value.
  mutating func clearF2() {self._f2 = nil}

  var f3: Int32 {
    get {_f3 ?? 0}
    set {_f3 = newValue}
  }
  /// Returns true if `f3` has been explicitly set.
  var hasF3: Bool {self._f3 != nil}
  /// Clears the value of `f3`. Subsequent reads from it will return its default value.
  mutating func clearF3() {self._f3 = nil}

  var f4: Int32 {
    get {_f4 ?? 0}
    set {_f4 = newValue}
  }
  /// Returns true if `f4` has been explicitly set.
  var hasF4: Bool {self._f4 != nil}
  /// Clears the value of `f4`. Subsequent reads from it will return its default value.
  mutating func clearF4() {self._f4 = nil}

  var f5: Int32 {
    get {_f5 ?? 0}
    set {_f5 = newValue}
  }
  /// Returns true if `f5` has been explicitly set.
  var hasF5: Bool {self._f5 != nil}
  /// Clears the value of `f5`. Subsequent reads from it will return its default value.
  mutating func clearF5() {self._f5 = nil}

  var f6: Int32 {
    get {_f6 ?? 0}
    set {_f6 = newValue}
  }
  /// Returns true if `f6` has been explicitly set.
  var hasF6: Bool {self._f6 != nil}
  /// Clears the value of `f6`. Subsequent reads from it will return its default value.
  mutating func clearF6() {self._f6 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
  fileprivate var _f2: Int32? = nil
  fileprivate var _f3: Int32? = nil
  fileprivate var _f4: Int32? = nil
  fileprivate var _f5: Int32? = nil
  fileprivate var _f6: Int32? = nil
}

/// popup_window. Parser 0x109c70: f1,f2 string; f3,f4 varint; f5,f6 string.
nonisolated struct DclientRpc_popup_window: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var name: Data {
    get {_name ?? Data()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  /// exact
  var displayName: Data {
    get {_displayName ?? Data()}
    set {_displayName = newValue}
  }
  /// Returns true if `displayName` has been explicitly set.
  var hasDisplayName: Bool {self._displayName != nil}
  /// Clears the value of `displayName`. Subsequent reads from it will return its default value.
  mutating func clearDisplayName() {self._displayName = nil}

  /// varint
  var f3: Int32 {
    get {_f3 ?? 0}
    set {_f3 = newValue}
  }
  /// Returns true if `f3` has been explicitly set.
  var hasF3: Bool {self._f3 != nil}
  /// Clears the value of `f3`. Subsequent reads from it will return its default value.
  mutating func clearF3() {self._f3 = nil}

  /// varint
  var f4: Int32 {
    get {_f4 ?? 0}
    set {_f4 = newValue}
  }
  /// Returns true if `f4` has been explicitly set.
  var hasF4: Bool {self._f4 != nil}
  /// Clears the value of `f4`. Subsequent reads from it will return its default value.
  mutating func clearF4() {self._f4 = nil}

  /// exact
  var command: Data {
    get {_command ?? Data()}
    set {_command = newValue}
  }
  /// Returns true if `command` has been explicitly set.
  var hasCommand: Bool {self._command != nil}
  /// Clears the value of `command`. Subsequent reads from it will return its default value.
  mutating func clearCommand() {self._command = nil}

  /// exact
  var options: Data {
    get {_options ?? Data()}
    set {_options = newValue}
  }
  /// Returns true if `options` has been explicitly set.
  var hasOptions: Bool {self._options != nil}
  /// Clears the value of `options`. Subsequent reads from it will return its default value.
  mutating func clearOptions() {self._options = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _name: Data? = nil
  fileprivate var _displayName: Data? = nil
  fileprivate var _f3: Int32? = nil
  fileprivate var _f4: Int32? = nil
  fileprivate var _command: Data? = nil
  fileprivate var _options: Data? = nil
}

/// room_terrain_metadata. Parser 0x109090: fields 1..4, each packed+unpacked varint
/// => four repeated int32 arrays (terrain grid columns/rows).
nonisolated struct DclientRpc_room_terrain_metadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: [Int32] = []

  var f2: [Int32] = []

  var f3: [Int32] = []

  var f4: [Int32] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// button_configuration. Parser 0x10a300: f1 varint; f2,f3,f4 string.
nonisolated struct DclientRpc_button_configuration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// varint (button id/slot)
  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  /// exact
  var displayString: Data {
    get {_displayString ?? Data()}
    set {_displayString = newValue}
  }
  /// Returns true if `displayString` has been explicitly set.
  var hasDisplayString: Bool {self._displayString != nil}
  /// Clears the value of `displayString`. Subsequent reads from it will return its default value.
  mutating func clearDisplayString() {self._displayString = nil}

  /// exact
  var actionString: Data {
    get {_actionString ?? Data()}
    set {_actionString = newValue}
  }
  /// Returns true if `actionString` has been explicitly set.
  var hasActionString: Bool {self._actionString != nil}
  /// Clears the value of `actionString`. Subsequent reads from it will return its default value.
  mutating func clearActionString() {self._actionString = nil}

  /// exact (tooltip)
  var ttString: Data {
    get {_ttString ?? Data()}
    set {_ttString = newValue}
  }
  /// Returns true if `ttString` has been explicitly set.
  var hasTtString: Bool {self._ttString != nil}
  /// Clears the value of `ttString`. Subsequent reads from it will return its default value.
  mutating func clearTtString() {self._ttString = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
  fileprivate var _displayString: Data? = nil
  fileprivate var _actionString: Data? = nil
  fileprivate var _ttString: Data? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "dclient_rpc"

nonisolated extension DclientRpc_hpbar_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".hpbar_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{1}f2\0\u{1}f3\0\u{1}f4\0\u{1}f5\0\u{1}f6\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._f2) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._f3) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._f4) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._f5) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._f6) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._f2 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._f3 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._f4 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._f5 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._f6 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_hpbar_data, rhs: DclientRpc_hpbar_data) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs._f2 != rhs._f2 {return false}
    if lhs._f3 != rhs._f3 {return false}
    if lhs._f4 != rhs._f4 {return false}
    if lhs._f5 != rhs._f5 {return false}
    if lhs._f6 != rhs._f6 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_enemy_hp_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".enemy_hp_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enemy_name\0\u{1}f2\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._enemyName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._f2) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._enemyName {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._f2 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_enemy_hp_data, rhs: DclientRpc_enemy_hp_data) -> Bool {
    if lhs._enemyName != rhs._enemyName {return false}
    if lhs._f2 != rhs._f2 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_sky_and_time: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".sky_and_time"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{1}f2\0\u{1}f3\0\u{1}f4\0\u{1}f5\0\u{3}printed_time_of_day_string\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._f2) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._f3) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._f4) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._f5) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._printedTimeOfDayString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._f2 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._f3 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._f4 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._f5 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._printedTimeOfDayString {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_sky_and_time, rhs: DclientRpc_sky_and_time) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs._f2 != rhs._f2 {return false}
    if lhs._f3 != rhs._f3 {return false}
    if lhs._f4 != rhs._f4 {return false}
    if lhs._f5 != rhs._f5 {return false}
    if lhs._printedTimeOfDayString != rhs._printedTimeOfDayString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_exp_to_level: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".exp_to_level"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt32Field(value: &self.f1) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.f1.isEmpty {
      try visitor.visitPackedInt32Field(value: self.f1, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_exp_to_level, rhs: DclientRpc_exp_to_level) -> Bool {
    if lhs.f1 != rhs.f1 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_icon_bar_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".icon_bar_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{1}f2\0\u{1}f3\0\u{1}f4\0\u{1}f5\0\u{1}f6\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._f2) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._f3) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._f4) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._f5) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._f6) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._f2 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._f3 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._f4 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._f5 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._f6 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_icon_bar_data, rhs: DclientRpc_icon_bar_data) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs._f2 != rhs._f2 {return false}
    if lhs._f3 != rhs._f3 {return false}
    if lhs._f4 != rhs._f4 {return false}
    if lhs._f5 != rhs._f5 {return false}
    if lhs._f6 != rhs._f6 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_popup_window: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".popup_window"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}display_name\0\u{1}f3\0\u{1}f4\0\u{1}command\0\u{1}options\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._displayName) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._f3) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._f4) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self._command) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._options) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._displayName {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._f3 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._f4 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._command {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._options {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_popup_window, rhs: DclientRpc_popup_window) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._displayName != rhs._displayName {return false}
    if lhs._f3 != rhs._f3 {return false}
    if lhs._f4 != rhs._f4 {return false}
    if lhs._command != rhs._command {return false}
    if lhs._options != rhs._options {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_room_terrain_metadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".room_terrain_metadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{1}f2\0\u{1}f3\0\u{1}f4\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt32Field(value: &self.f1) }()
      case 2: try { try decoder.decodeRepeatedInt32Field(value: &self.f2) }()
      case 3: try { try decoder.decodeRepeatedInt32Field(value: &self.f3) }()
      case 4: try { try decoder.decodeRepeatedInt32Field(value: &self.f4) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.f1.isEmpty {
      try visitor.visitPackedInt32Field(value: self.f1, fieldNumber: 1)
    }
    if !self.f2.isEmpty {
      try visitor.visitPackedInt32Field(value: self.f2, fieldNumber: 2)
    }
    if !self.f3.isEmpty {
      try visitor.visitPackedInt32Field(value: self.f3, fieldNumber: 3)
    }
    if !self.f4.isEmpty {
      try visitor.visitPackedInt32Field(value: self.f4, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_room_terrain_metadata, rhs: DclientRpc_room_terrain_metadata) -> Bool {
    if lhs.f1 != rhs.f1 {return false}
    if lhs.f2 != rhs.f2 {return false}
    if lhs.f3 != rhs.f3 {return false}
    if lhs.f4 != rhs.f4 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension DclientRpc_button_configuration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".button_configuration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{3}display_string\0\u{3}action_string\0\u{3}tt_string\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._displayString) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._actionString) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._ttString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._displayString {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._actionString {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._ttString {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: DclientRpc_button_configuration, rhs: DclientRpc_button_configuration) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs._displayString != rhs._displayString {return false}
    if lhs._actionString != rhs._actionString {return false}
    if lhs._ttString != rhs._ttString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
