// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xirr_soundpack_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AlterAeon dclient RPC — soundpack.
/// Package xirr_soundpack_rpc, from xirr_soundpack_rpc.pb.cc in dclient_linux64 1.105-g64-rc2.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// op enum values (from provided schema / SetSystemMusic dispatch). Not a proto
/// enum on the wire (field is a plain int32); listed for reference.
nonisolated enum XirrSoundpackRpc_MusicOp: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case invalid = 0
  case channelCreate = 1
  case channelDelete = 2
  case configure = 3
  case hardStartPlayout = 4
  case hardStop = 5
  case hardSuspend = 6
  case hardUnsuspend = 7
  case softStartPlayout = 8
  case softStop = 9
  case softSuspend = 10
  case softUnsuspend = 11
  case setFadein = 12
  case setFadeout = 13
  case setLoop = 14

  init() {
    self = .invalid
  }

}

/// music_playout_data. Parser 0x133bb0 VERIFIED: tags 0x0a,0x10,0x18,0x20,0x28,0x52
/// => fields 1,2,3,4,5,10 exactly matching the provided schema.
nonisolated struct XirrSoundpackRpc_music_playout_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var channelName: String {
    get {_channelName ?? String()}
    set {_channelName = newValue}
  }
  /// Returns true if `channelName` has been explicitly set.
  var hasChannelName: Bool {self._channelName != nil}
  /// Clears the value of `channelName`. Subsequent reads from it will return its default value.
  mutating func clearChannelName() {self._channelName = nil}

  /// enum-valued (see MusicOp)
  var op: Int32 {
    get {_op ?? 0}
    set {_op = newValue}
  }
  /// Returns true if `op` has been explicitly set.
  var hasOp: Bool {self._op != nil}
  /// Clears the value of `op`. Subsequent reads from it will return its default value.
  mutating func clearOp() {self._op = nil}

  var fadein: Int32 {
    get {_fadein ?? 0}
    set {_fadein = newValue}
  }
  /// Returns true if `fadein` has been explicitly set.
  var hasFadein: Bool {self._fadein != nil}
  /// Clears the value of `fadein`. Subsequent reads from it will return its default value.
  mutating func clearFadein() {self._fadein = nil}

  var fadeout: Int32 {
    get {_fadeout ?? 0}
    set {_fadeout = newValue}
  }
  /// Returns true if `fadeout` has been explicitly set.
  var hasFadeout: Bool {self._fadeout != nil}
  /// Clears the value of `fadeout`. Subsequent reads from it will return its default value.
  mutating func clearFadeout() {self._fadeout = nil}

  var loop: Int32 {
    get {_loop ?? 0}
    set {_loop = newValue}
  }
  /// Returns true if `loop` has been explicitly set.
  var hasLoop: Bool {self._loop != nil}
  /// Clears the value of `loop`. Subsequent reads from it will return its default value.
  mutating func clearLoop() {self._loop = nil}

  /// exact
  var filename: String {
    get {_filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  var hasFilename: Bool {self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  mutating func clearFilename() {self._filename = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _channelName: String? = nil
  fileprivate var _op: Int32? = nil
  fileprivate var _fadein: Int32? = nil
  fileprivate var _fadeout: Int32? = nil
  fileprivate var _loop: Int32? = nil
  fileprivate var _filename: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "xirr_soundpack_rpc"

nonisolated extension XirrSoundpackRpc_MusicOp: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INVALID\0\u{1}CHANNEL_CREATE\0\u{1}CHANNEL_DELETE\0\u{1}CONFIGURE\0\u{1}HARD_START_PLAYOUT\0\u{1}HARD_STOP\0\u{1}HARD_SUSPEND\0\u{1}HARD_UNSUSPEND\0\u{1}SOFT_START_PLAYOUT\0\u{1}SOFT_STOP\0\u{1}SOFT_SUSPEND\0\u{1}SOFT_UNSUSPEND\0\u{1}SET_FADEIN\0\u{1}SET_FADEOUT\0\u{1}SET_LOOP\0")
}

nonisolated extension XirrSoundpackRpc_music_playout_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".music_playout_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_name\0\u{1}op\0\u{1}fadein\0\u{1}fadeout\0\u{1}loop\0\u{2}\u{5}filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._channelName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._op) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._fadein) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._fadeout) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._loop) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._channelName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._op {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._fadein {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._fadeout {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._loop {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrSoundpackRpc_music_playout_data, rhs: XirrSoundpackRpc_music_playout_data) -> Bool {
    if lhs._channelName != rhs._channelName {return false}
    if lhs._op != rhs._op {return false}
    if lhs._fadein != rhs._fadein {return false}
    if lhs._fadeout != rhs._fadeout {return false}
    if lhs._loop != rhs._loop {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
