// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xirr_client_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AlterAeon dclient RPC — client_rpc payloads.
/// Package xirr_client_rpc, from xci_rpc_socket_generic.pb.cc in dclient_linux64 1.105-g64-rc2.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// version_info. Parser 0x140440: f1,f2,f3 all string. These are OUR outbound identity fields
/// (always valid UTF-8, we set them) so they stay `string`.
nonisolated struct XirrClientRpc_version_info: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var clientVersion: String {
    get {_clientVersion ?? String()}
    set {_clientVersion = newValue}
  }
  /// Returns true if `clientVersion` has been explicitly set.
  var hasClientVersion: Bool {self._clientVersion != nil}
  /// Clears the value of `clientVersion`. Subsequent reads from it will return its default value.
  mutating func clearClientVersion() {self._clientVersion = nil}

  /// exact
  var clientUuid: String {
    get {_clientUuid ?? String()}
    set {_clientUuid = newValue}
  }
  /// Returns true if `clientUuid` has been explicitly set.
  var hasClientUuid: Bool {self._clientUuid != nil}
  /// Clears the value of `clientUuid`. Subsequent reads from it will return its default value.
  mutating func clearClientUuid() {self._clientUuid = nil}

  /// exact
  var clientProtocol: String {
    get {_clientProtocol ?? String()}
    set {_clientProtocol = newValue}
  }
  /// Returns true if `clientProtocol` has been explicitly set.
  var hasClientProtocol: Bool {self._clientProtocol != nil}
  /// Clears the value of `clientProtocol`. Subsequent reads from it will return its default value.
  mutating func clearClientProtocol() {self._clientProtocol = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _clientVersion: String? = nil
  fileprivate var _clientUuid: String? = nil
  fileprivate var _clientProtocol: String? = nil
}

/// text_block. Parser 0x140200: f1 (main text), f2 extra_info. Carry raw game output (ANSI + Latin-1),
/// which is NOT valid UTF-8 — declared `bytes` so SwiftProtobuf won't reject the message.
nonisolated struct XirrClientRpc_text_block: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// NAME UNRECOVERED (field-1, block body)
  var text: Data {
    get {_text ?? Data()}
    set {_text = newValue}
  }
  /// Returns true if `text` has been explicitly set.
  var hasText: Bool {self._text != nil}
  /// Clears the value of `text`. Subsequent reads from it will return its default value.
  mutating func clearText() {self._text = nil}

  /// exact
  var extraInfo: Data {
    get {_extraInfo ?? Data()}
    set {_extraInfo = newValue}
  }
  /// Returns true if `extraInfo` has been explicitly set.
  var hasExtraInfo: Bool {self._extraInfo != nil}
  /// Clears the value of `extraInfo`. Subsequent reads from it will return its default value.
  mutating func clearExtraInfo() {self._extraInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _text: Data? = nil
  fileprivate var _extraInfo: Data? = nil
}

/// generic_kv_event. Parser 0x13dad0: f1,f2 string, f3 varint. May carry game text → bytes.
nonisolated struct XirrClientRpc_generic_kv_event: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var key: Data {
    get {_key ?? Data()}
    set {_key = newValue}
  }
  /// Returns true if `key` has been explicitly set.
  var hasKey: Bool {self._key != nil}
  /// Clears the value of `key`. Subsequent reads from it will return its default value.
  mutating func clearKey() {self._key = nil}

  /// exact
  var kvalue: Data {
    get {_kvalue ?? Data()}
    set {_kvalue = newValue}
  }
  /// Returns true if `kvalue` has been explicitly set.
  var hasKvalue: Bool {self._kvalue != nil}
  /// Clears the value of `kvalue`. Subsequent reads from it will return its default value.
  mutating func clearKvalue() {self._kvalue = nil}

  /// varint
  var f3: Int32 {
    get {_f3 ?? 0}
    set {_f3 = newValue}
  }
  /// Returns true if `f3` has been explicitly set.
  var hasF3: Bool {self._f3 != nil}
  /// Clears the value of `f3`. Subsequent reads from it will return its default value.
  mutating func clearF3() {self._f3 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _key: Data? = nil
  fileprivate var _kvalue: Data? = nil
  fileprivate var _f3: Int32? = nil
}

/// channel_send_data. Parser 0x13dfc0: f1,f2 string. `sent_message` is chat text (ANSI/Latin-1) → bytes.
nonisolated struct XirrClientRpc_channel_send_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var channelName: Data {
    get {_channelName ?? Data()}
    set {_channelName = newValue}
  }
  /// Returns true if `channelName` has been explicitly set.
  var hasChannelName: Bool {self._channelName != nil}
  /// Clears the value of `channelName`. Subsequent reads from it will return its default value.
  mutating func clearChannelName() {self._channelName = nil}

  /// exact
  var sentMessage: Data {
    get {_sentMessage ?? Data()}
    set {_sentMessage = newValue}
  }
  /// Returns true if `sentMessage` has been explicitly set.
  var hasSentMessage: Bool {self._sentMessage != nil}
  /// Clears the value of `sentMessage`. Subsequent reads from it will return its default value.
  mutating func clearSentMessage() {self._sentMessage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _channelName: Data? = nil
  fileprivate var _sentMessage: Data? = nil
}

/// audio_playout_data. Parser 0x13ddc0: single string field 1 (a filename; ASCII, but bytes for safety).
nonisolated struct XirrClientRpc_audio_playout_data: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// exact
  var shortClipFilename: Data {
    get {_shortClipFilename ?? Data()}
    set {_shortClipFilename = newValue}
  }
  /// Returns true if `shortClipFilename` has been explicitly set.
  var hasShortClipFilename: Bool {self._shortClipFilename != nil}
  /// Clears the value of `shortClipFilename`. Subsequent reads from it will return its default value.
  mutating func clearShortClipFilename() {self._shortClipFilename = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _shortClipFilename: Data? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "xirr_client_rpc"

nonisolated extension XirrClientRpc_version_info: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".version_info"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_version\0\u{3}client_uuid\0\u{3}client_protocol\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._clientVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._clientUuid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._clientProtocol) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._clientVersion {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._clientUuid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._clientProtocol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrClientRpc_version_info, rhs: XirrClientRpc_version_info) -> Bool {
    if lhs._clientVersion != rhs._clientVersion {return false}
    if lhs._clientUuid != rhs._clientUuid {return false}
    if lhs._clientProtocol != rhs._clientProtocol {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension XirrClientRpc_text_block: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".text_block"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}extra_info\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._text) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._extraInfo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._text {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._extraInfo {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrClientRpc_text_block, rhs: XirrClientRpc_text_block) -> Bool {
    if lhs._text != rhs._text {return false}
    if lhs._extraInfo != rhs._extraInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension XirrClientRpc_generic_kv_event: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".generic_kv_event"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}kvalue\0\u{1}f3\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._key) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._kvalue) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._f3) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._key {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._kvalue {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._f3 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrClientRpc_generic_kv_event, rhs: XirrClientRpc_generic_kv_event) -> Bool {
    if lhs._key != rhs._key {return false}
    if lhs._kvalue != rhs._kvalue {return false}
    if lhs._f3 != rhs._f3 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension XirrClientRpc_channel_send_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".channel_send_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_name\0\u{3}sent_message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._channelName) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._sentMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._channelName {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._sentMessage {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrClientRpc_channel_send_data, rhs: XirrClientRpc_channel_send_data) -> Bool {
    if lhs._channelName != rhs._channelName {return false}
    if lhs._sentMessage != rhs._sentMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension XirrClientRpc_audio_playout_data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".audio_playout_data"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}short_clip_filename\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._shortClipFilename) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._shortClipFilename {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrClientRpc_audio_playout_data, rhs: XirrClientRpc_audio_playout_data) -> Bool {
    if lhs._shortClipFilename != rhs._shortClipFilename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
