// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xirr_server_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AlterAeon dclient RPC — server_rpc.
/// Package xirr_server_rpc, from xirr_rpc_keepalive.pb.cc in dclient_linux64 1.105-g64-rc2.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// keepalive_info. Parser 0x165a00: single varint field 1 (latency/seq ms).
nonisolated struct XirrServerRpc_keepalive_info: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// varint (see "keepalive latency of %d ms")
  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "xirr_server_rpc"

nonisolated extension XirrServerRpc_keepalive_info: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".keepalive_info"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrServerRpc_keepalive_info, rhs: XirrServerRpc_keepalive_info) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
