// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xirr_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AlterAeon dclient RPC — framing + channel auth.
/// Package xirr_rpc, from xirr_proto_framer_frameinfo.pb.cc and the auth .pb.cc
/// in dclient_linux64 1.105-g64-rc2.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The per-message routing header. Sent as the FIRST of the two line-frames that
/// make up one logical RPC block (the "proto frame"); the SECOND line-frame ("data
/// frame") carries the serialized payload message selected by proto_name.
/// Parser 0x1623d0 (2-byte tags for high field numbers). String field names exact.
nonisolated struct XirrRpc_xirr_proto_framer_frameinfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// routing key: payload message type
  var protoName: String {
    get {_protoName ?? String()}
    set {_protoName = newValue}
  }
  /// Returns true if `protoName` has been explicitly set.
  var hasProtoName: Bool {self._protoName != nil}
  /// Clears the value of `protoName`. Subsequent reads from it will return its default value.
  mutating func clearProtoName() {self._protoName = nil}

  var f2: Int32 {
    get {_f2 ?? 0}
    set {_f2 = newValue}
  }
  /// Returns true if `f2` has been explicitly set.
  var hasF2: Bool {self._f2 != nil}
  /// Clears the value of `f2`. Subsequent reads from it will return its default value.
  mutating func clearF2() {self._f2 = nil}

  /// exact (service key, e.g. "hpbar")
  var rpcServiceName: String {
    get {_rpcServiceName ?? String()}
    set {_rpcServiceName = newValue}
  }
  /// Returns true if `rpcServiceName` has been explicitly set.
  var hasRpcServiceName: Bool {self._rpcServiceName != nil}
  /// Clears the value of `rpcServiceName`. Subsequent reads from it will return its default value.
  mutating func clearRpcServiceName() {self._rpcServiceName = nil}

  var f11: Int32 {
    get {_f11 ?? 0}
    set {_f11 = newValue}
  }
  /// Returns true if `f11` has been explicitly set.
  var hasF11: Bool {self._f11 != nil}
  /// Clears the value of `f11`. Subsequent reads from it will return its default value.
  mutating func clearF11() {self._f11 = nil}

  var f20: Int32 {
    get {_f20 ?? 0}
    set {_f20 = newValue}
  }
  /// Returns true if `f20` has been explicitly set.
  var hasF20: Bool {self._f20 != nil}
  /// Clears the value of `f20`. Subsequent reads from it will return its default value.
  mutating func clearF20() {self._f20 = nil}

  /// provided schema: int64
  var f30: Int64 {
    get {_f30 ?? 0}
    set {_f30 = newValue}
  }
  /// Returns true if `f30` has been explicitly set.
  var hasF30: Bool {self._f30 != nil}
  /// Clears the value of `f30`. Subsequent reads from it will return its default value.
  mutating func clearF30() {self._f30 = nil}

  var f31: Int32 {
    get {_f31 ?? 0}
    set {_f31 = newValue}
  }
  /// Returns true if `f31` has been explicitly set.
  var hasF31: Bool {self._f31 != nil}
  /// Clears the value of `f31`. Subsequent reads from it will return its default value.
  mutating func clearF31() {self._f31 = nil}

  var f90: Int32 {
    get {_f90 ?? 0}
    set {_f90 = newValue}
  }
  /// Returns true if `f90` has been explicitly set.
  var hasF90: Bool {self._f90 != nil}
  /// Clears the value of `f90`. Subsequent reads from it will return its default value.
  mutating func clearF90() {self._f90 = nil}

  /// exact
  var failureMessage: String {
    get {_failureMessage ?? String()}
    set {_failureMessage = newValue}
  }
  /// Returns true if `failureMessage` has been explicitly set.
  var hasFailureMessage: Bool {self._failureMessage != nil}
  /// Clears the value of `failureMessage`. Subsequent reads from it will return its default value.
  mutating func clearFailureMessage() {self._failureMessage = nil}

  var f99: Int32 {
    get {_f99 ?? 0}
    set {_f99 = newValue}
  }
  /// Returns true if `f99` has been explicitly set.
  var hasF99: Bool {self._f99 != nil}
  /// Clears the value of `f99`. Subsequent reads from it will return its default value.
  mutating func clearF99() {self._f99 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _protoName: String? = nil
  fileprivate var _f2: Int32? = nil
  fileprivate var _rpcServiceName: String? = nil
  fileprivate var _f11: Int32? = nil
  fileprivate var _f20: Int32? = nil
  fileprivate var _f30: Int64? = nil
  fileprivate var _f31: Int32? = nil
  fileprivate var _f90: Int32? = nil
  fileprivate var _failureMessage: String? = nil
  fileprivate var _f99: Int32? = nil
}

/// Channel authentication handshake. Parser 0x164130 VERIFIED: every tag confirmed
/// (0x08,0x52,0x5a,0x62,0xa2,0xaa,0xb2,0xf0,0xfa) => the field numbers below.
/// (Auth semantics owned by another agent; schema included for completeness.)
nonisolated struct XirrRpc_xirr_rpc_channel_auth: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: Int32 {
    get {_f1 ?? 0}
    set {_f1 = newValue}
  }
  /// Returns true if `f1` has been explicitly set.
  var hasF1: Bool {self._f1 != nil}
  /// Clears the value of `f1`. Subsequent reads from it will return its default value.
  mutating func clearF1() {self._f1 = nil}

  /// exact
  var clientNonce: String {
    get {_clientNonce ?? String()}
    set {_clientNonce = newValue}
  }
  /// Returns true if `clientNonce` has been explicitly set.
  var hasClientNonce: Bool {self._clientNonce != nil}
  /// Clears the value of `clientNonce`. Subsequent reads from it will return its default value.
  mutating func clearClientNonce() {self._clientNonce = nil}

  /// exact
  var clientHash: String {
    get {_clientHash ?? String()}
    set {_clientHash = newValue}
  }
  /// Returns true if `clientHash` has been explicitly set.
  var hasClientHash: Bool {self._clientHash != nil}
  /// Clears the value of `clientHash`. Subsequent reads from it will return its default value.
  mutating func clearClientHash() {self._clientHash = nil}

  /// exact
  var clientPublicKey: String {
    get {_clientPublicKey ?? String()}
    set {_clientPublicKey = newValue}
  }
  /// Returns true if `clientPublicKey` has been explicitly set.
  var hasClientPublicKey: Bool {self._clientPublicKey != nil}
  /// Clears the value of `clientPublicKey`. Subsequent reads from it will return its default value.
  mutating func clearClientPublicKey() {self._clientPublicKey = nil}

  /// exact
  var serverNonce: String {
    get {_serverNonce ?? String()}
    set {_serverNonce = newValue}
  }
  /// Returns true if `serverNonce` has been explicitly set.
  var hasServerNonce: Bool {self._serverNonce != nil}
  /// Clears the value of `serverNonce`. Subsequent reads from it will return its default value.
  mutating func clearServerNonce() {self._serverNonce = nil}

  /// exact
  var serverHash: String {
    get {_serverHash ?? String()}
    set {_serverHash = newValue}
  }
  /// Returns true if `serverHash` has been explicitly set.
  var hasServerHash: Bool {self._serverHash != nil}
  /// Clears the value of `serverHash`. Subsequent reads from it will return its default value.
  mutating func clearServerHash() {self._serverHash = nil}

  /// exact
  var serverPublicKey: String {
    get {_serverPublicKey ?? String()}
    set {_serverPublicKey = newValue}
  }
  /// Returns true if `serverPublicKey` has been explicitly set.
  var hasServerPublicKey: Bool {self._serverPublicKey != nil}
  /// Clears the value of `serverPublicKey`. Subsequent reads from it will return its default value.
  mutating func clearServerPublicKey() {self._serverPublicKey = nil}

  var f30: Int32 {
    get {_f30 ?? 0}
    set {_f30 = newValue}
  }
  /// Returns true if `f30` has been explicitly set.
  var hasF30: Bool {self._f30 != nil}
  /// Clears the value of `f30`. Subsequent reads from it will return its default value.
  mutating func clearF30() {self._f30 = nil}

  /// exact
  var serverFailString: String {
    get {_serverFailString ?? String()}
    set {_serverFailString = newValue}
  }
  /// Returns true if `serverFailString` has been explicitly set.
  var hasServerFailString: Bool {self._serverFailString != nil}
  /// Clears the value of `serverFailString`. Subsequent reads from it will return its default value.
  mutating func clearServerFailString() {self._serverFailString = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _f1: Int32? = nil
  fileprivate var _clientNonce: String? = nil
  fileprivate var _clientHash: String? = nil
  fileprivate var _clientPublicKey: String? = nil
  fileprivate var _serverNonce: String? = nil
  fileprivate var _serverHash: String? = nil
  fileprivate var _serverPublicKey: String? = nil
  fileprivate var _f30: Int32? = nil
  fileprivate var _serverFailString: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "xirr_rpc"

nonisolated extension XirrRpc_xirr_proto_framer_frameinfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".xirr_proto_framer_frameinfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}proto_name\0\u{1}f2\0\u{4}\u{8}rpc_service_name\0\u{1}f11\0\u{2}\u{9}f20\0\u{2}\u{a}f30\0\u{1}f31\0\u{2};f90\0\u{3}failure_message\0\u{2}\u{8}f99\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._protoName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._f2) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._rpcServiceName) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self._f11) }()
      case 20: try { try decoder.decodeSingularInt32Field(value: &self._f20) }()
      case 30: try { try decoder.decodeSingularInt64Field(value: &self._f30) }()
      case 31: try { try decoder.decodeSingularInt32Field(value: &self._f31) }()
      case 90: try { try decoder.decodeSingularInt32Field(value: &self._f90) }()
      case 91: try { try decoder.decodeSingularStringField(value: &self._failureMessage) }()
      case 99: try { try decoder.decodeSingularInt32Field(value: &self._f99) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._protoName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._f2 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._rpcServiceName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._f11 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._f20 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 20)
    } }()
    try { if let v = self._f30 {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 30)
    } }()
    try { if let v = self._f31 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 31)
    } }()
    try { if let v = self._f90 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 90)
    } }()
    try { if let v = self._failureMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 91)
    } }()
    try { if let v = self._f99 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 99)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrRpc_xirr_proto_framer_frameinfo, rhs: XirrRpc_xirr_proto_framer_frameinfo) -> Bool {
    if lhs._protoName != rhs._protoName {return false}
    if lhs._f2 != rhs._f2 {return false}
    if lhs._rpcServiceName != rhs._rpcServiceName {return false}
    if lhs._f11 != rhs._f11 {return false}
    if lhs._f20 != rhs._f20 {return false}
    if lhs._f30 != rhs._f30 {return false}
    if lhs._f31 != rhs._f31 {return false}
    if lhs._f90 != rhs._f90 {return false}
    if lhs._failureMessage != rhs._failureMessage {return false}
    if lhs._f99 != rhs._f99 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension XirrRpc_xirr_rpc_channel_auth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".xirr_rpc_channel_auth"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{4}\u{9}client_nonce\0\u{3}client_hash\0\u{3}client_public_key\0\u{4}\u{8}server_nonce\0\u{3}server_hash\0\u{3}server_public_key\0\u{2}\u{8}f30\0\u{3}server_fail_string\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._f1) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._clientNonce) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self._clientHash) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._clientPublicKey) }()
      case 20: try { try decoder.decodeSingularStringField(value: &self._serverNonce) }()
      case 21: try { try decoder.decodeSingularStringField(value: &self._serverHash) }()
      case 22: try { try decoder.decodeSingularStringField(value: &self._serverPublicKey) }()
      case 30: try { try decoder.decodeSingularInt32Field(value: &self._f30) }()
      case 31: try { try decoder.decodeSingularStringField(value: &self._serverFailString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._f1 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._clientNonce {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._clientHash {
      try visitor.visitSingularStringField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._clientPublicKey {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._serverNonce {
      try visitor.visitSingularStringField(value: v, fieldNumber: 20)
    } }()
    try { if let v = self._serverHash {
      try visitor.visitSingularStringField(value: v, fieldNumber: 21)
    } }()
    try { if let v = self._serverPublicKey {
      try visitor.visitSingularStringField(value: v, fieldNumber: 22)
    } }()
    try { if let v = self._f30 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 30)
    } }()
    try { if let v = self._serverFailString {
      try visitor.visitSingularStringField(value: v, fieldNumber: 31)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: XirrRpc_xirr_rpc_channel_auth, rhs: XirrRpc_xirr_rpc_channel_auth) -> Bool {
    if lhs._f1 != rhs._f1 {return false}
    if lhs._clientNonce != rhs._clientNonce {return false}
    if lhs._clientHash != rhs._clientHash {return false}
    if lhs._clientPublicKey != rhs._clientPublicKey {return false}
    if lhs._serverNonce != rhs._serverNonce {return false}
    if lhs._serverHash != rhs._serverHash {return false}
    if lhs._serverPublicKey != rhs._serverPublicKey {return false}
    if lhs._f30 != rhs._f30 {return false}
    if lhs._serverFailString != rhs._serverFailString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
